worker_processes 1;
error_log /var/log/nginx/error.log warn;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout 65;

    server {
        listen 5174;
        server_name _;
        root /var/www/converter;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }

    server {
        listen 5175;
        server_name _;
        root /var/www/scraper;
        index index.html;

        location /scraper-api/ {
            proxy_pass https://new-scrapper-provider-dev.internal.production.gm.paytmmoney.com/;
            proxy_ssl_server_name on;
            proxy_set_header Host new-scrapper-provider-dev.internal.production.gm.paytmmoney.com;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }

    server {
        listen 5176;
        server_name _;
        root /var/www/examiner-hub;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
